name: GitHub - Activity - Readme

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Lorenzo0111/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.FEED_TOKEN }}
        with:
          COMMIT_MSG: '🤖[Automated] Update README with GitHub Activity'
          COMMIT_NAME: 'gantoin'
          COMMIT_EMAIL: 'gantoin@pm.me'
